require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

MultipleMemoizedHelpers:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]
