require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'config/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf
